# at hwayoung

main : main.c
	gcc main.c -I/home/hwayoung/TeamProject/Project/hwayoung/ui/include -lpthread -L/home/hwayoung/TeamProject/Project/hwayoung/ui/lib -lhwayounglib -o main

clean:
	rm -f main
