# total makefile

all :makeMatch makeUI makeTotal 

makeTotal:
	make -C hwayoung;
	
makeUI:
	make -C hwayoung/ui/lib;

makeMatch:
	make -C hayoung/lib;
	
clean:
	make clean -C hwayoung/ui/lib;
	make clean -C hayoung/lib;
	make clean -C hwayoung;
